#!/usr/bin/env bash
# Regenerate requirements-lock.txt from the project venv (Python 3.12).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

PYTHON="${PYTHON:-python3.12}"
if ! command -v "$PYTHON" >/dev/null 2>&1; then
  echo "error: $PYTHON not found (need Python 3.10–3.12 for aider-chat)" >&2
  exit 1
fi

if [[ ! -d .venv ]]; then
  "$PYTHON" -m venv .venv
fi

# shellcheck source=/dev/null
source .venv/bin/activate
python -m pip install -U pip wheel
pip install -e ".[dev]"

{
  echo "# Pinned transitive dependencies for mcp-coder (runtime)."
  echo "# Generated by: ./scripts/lock-deps.sh"
  echo "# Python: $(python --version 2>&1)"
  echo "# Date: $(date -u +%Y-%m-%d)"
  echo "#"
  echo "# Install: ./scripts/bootstrap.sh --locked"
  echo "# Or: pip install -r requirements-lock.txt && pip install -e . --no-deps"
  echo ""
  pip freeze | grep -v '^-e ' | grep -v '^mcp-coder'
} > requirements-lock.txt

echo "Wrote requirements-lock.txt ($(wc -l < requirements-lock.txt | tr -d ' ') lines)"
